### Получение списка новых заданий
GET http://localhost:3004/tasks/new?page=1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4OGEzMDM0NS1mMWM2LTRiYTgtOGU4Mi0xYmJiMzQ0NDkxN2UiLCJlbWFpbCI6ImpvaG40QGRvZS5jb20iLCJyb2xlSWQiOjIsImxhc3RuYW1lIjoiUnVzc2VsIiwiZmlyc3RuYW1lIjoiSmFjayIsImlhdCI6MTcwNjgxODMyOCwiZXhwIjoxNzA2ODE4NjI4fQ.qBq1wccWIfNB3wjCjN5bCzXmxAkFnroWTXW3ymb-J7Y



### Получение собственных заданий
GET http://localhost:3004/tasks/my HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4OGEzMDM0NS1mMWM2LTRiYTgtOGU4Mi0xYmJiMzQ0NDkxN2UiLCJlbWFpbCI6ImpvaG40QGRvZS5jb20iLCJyb2xlSWQiOjIsImxhc3RuYW1lIjoiUnVzc2VsIiwiZmlyc3RuYW1lIjoiSmFjayIsImlhdCI6MTcwNjgyMjI1MSwiZXhwIjoxNzA2ODIyNTUxfQ.Ss46vOy5ZqcLxVj-GuWc6QVlk_QakgBGPKWqDr4fZos



### Получение детальной информации о задании
GET http://localhost:3004/tasks/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmNGE5ODFlMy03M2QwLTQxZTktODk0OS04ZjgxZGRlOGMxNmMiLCJlbWFpbCI6ImpvaG4zQGRvZS5jb20iLCJyb2xlSWQiOjEsImxhc3RuYW1lIjoiRG9lIiwiZmlyc3RuYW1lIjoiSm9obiIsImlhdCI6MTcwNjgxNzkxNywiZXhwIjoxNzA2ODE4MjE3fQ.cRHZaqwOLXZtRqyFNuV7UK-ncI5xN_GOF8-JUHAImQk



### Создание нового задания
POST http://localhost:3004/tasks HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmNGE5ODFlMy03M2QwLTQxZTktODk0OS04ZjgxZGRlOGMxNmMiLCJlbWFpbCI6ImpvaG4zQGRvZS5jb20iLCJyb2xlSWQiOjEsImxhc3RuYW1lIjoiRG9lIiwiZmlyc3RuYW1lIjoiSm9obiIsImlhdCI6MTcwNjgyMTkzMywiZXhwIjoxNzA2ODIyMjMzfQ.E8XrwZv0FVybSlTlsUoHYEAD0YR5JtV5nnirH_uFJ9I

{
  "title": "Task long long title",
  "description": "Objectively procrastinate dynamic imperatives without customer directed niches. Proactively productivate interdependent e-commerce and transparent methodologies.",
  "category": "repair",
  "cityId": 3,
  "price": 1000,
  "tags": ["plaster"],
  "executionDate": "2024-12-15",
  "address": "Moscow, Presnenskaya embankment, 12, office No. 2"
}



### Откликнуться на задание
PATCH  http://localhost:3004/tasks/1/responses HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4OGEzMDM0NS1mMWM2LTRiYTgtOGU4Mi0xYmJiMzQ0NDkxN2UiLCJlbWFpbCI6ImpvaG40QGRvZS5jb20iLCJyb2xlSWQiOjIsImxhc3RuYW1lIjoiUnVzc2VsIiwiZmlyc3RuYW1lIjoiSmFjayIsImlhdCI6MTcwNjgyMTk2MSwiZXhwIjoxNzA2ODIyMjYxfQ.3n_Ki1cI0PhkNyuABZfT6xSZKFxX1SiN2co8xcfnnBk



### Выбор исполнителя для задания
PATCH  http://localhost:3004/tasks/1/contractor HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4OGEzMDM0NS1mMWM2LTRiYTgtOGU4Mi0xYmJiMzQ0NDkxN2UiLCJlbWFpbCI6ImpvaG40QGRvZS5jb20iLCJyb2xlSWQiOjIsImxhc3RuYW1lIjoiUnVzc2VsIiwiZmlyc3RuYW1lIjoiSmFjayIsImlhdCI6MTcwNjgyMjI1MSwiZXhwIjoxNzA2ODIyNTUxfQ.Ss46vOy5ZqcLxVj-GuWc6QVlk_QakgBGPKWqDr4fZos

{
  "contractorId": "88a30345-f1c6-4ba8-8e82-1bbb3444917e"
}



### Обновление статуса задания
PATCH http://localhost:3004/tasks/1/status HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4OGEzMDM0NS1mMWM2LTRiYTgtOGU4Mi0xYmJiMzQ0NDkxN2UiLCJlbWFpbCI6ImpvaG40QGRvZS5jb20iLCJyb2xlSWQiOjIsImxhc3RuYW1lIjoiUnVzc2VsIiwiZmlyc3RuYW1lIjoiSmFjayIsImlhdCI6MTcwNjgyMjI1MSwiZXhwIjoxNzA2ODIyNTUxfQ.Ss46vOy5ZqcLxVj-GuWc6QVlk_QakgBGPKWqDr4fZos

{
  "statusId": 2
}



### Удаление существующего задания
DELETE http://localhost:3004/tasks/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmNGE5ODFlMy03M2QwLTQxZTktODk0OS04ZjgxZGRlOGMxNmMiLCJlbWFpbCI6ImpvaG4zQGRvZS5jb20iLCJyb2xlSWQiOjEsImxhc3RuYW1lIjoiRG9lIiwiZmlyc3RuYW1lIjoiSm9obiIsImlhdCI6MTcwNjgyMTE3NywiZXhwIjoxNzA2ODIxNDc3fQ.aOaJzWp6tXucCvNsHc__Ucad7S47XcB7zi4gha5lGro



### Рассылка новых заданий исполнителям
GET http://localhost:3004/tasks/new/notification HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4OGEzMDM0NS1mMWM2LTRiYTgtOGU4Mi0xYmJiMzQ0NDkxN2UiLCJlbWFpbCI6ImpvaG40QGRvZS5jb20iLCJyb2xlSWQiOjIsImxhc3RuYW1lIjoiUnVzc2VsIiwiZmlyc3RuYW1lIjoiSmFjayIsImlhdCI6MTcwNjgyMDYxMSwiZXhwIjoxNzA2ODIwOTExfQ.4iiFPUde_9JC0d6RabCQK5lTL-kKtkvZs9kjQvrY4DQ



### Создание новой категории
POST http://localhost:3004/tasks/categories HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmNGE5ODFlMy03M2QwLTQxZTktODk0OS04ZjgxZGRlOGMxNmMiLCJlbWFpbCI6ImpvaG4zQGRvZS5jb20iLCJyb2xlSWQiOjEsImxhc3RuYW1lIjoiRG9lIiwiZmlyc3RuYW1lIjoiSm9obiIsImlhdCI6MTcwNjgyMTE3NywiZXhwIjoxNzA2ODIxNDc3fQ.aOaJzWp6tXucCvNsHc__Ucad7S47XcB7zi4gha5lGro

{
  "name": "building"
}



### Создание отзыва об исполнителе задания
POST http://localhost:3004/tasks/reviews HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmNGE5ODFlMy03M2QwLTQxZTktODk0OS04ZjgxZGRlOGMxNmMiLCJlbWFpbCI6ImpvaG4zQGRvZS5jb20iLCJyb2xlSWQiOjEsImxhc3RuYW1lIjoiRG9lIiwiZmlyc3RuYW1lIjoiSm9obiIsImlhdCI6MTcwNjgyMDAyNSwiZXhwIjoxNzA2ODIwMzI1fQ.Z3v-yOoZ0XcjTdEZxZdHWWxdIQUxs57mPnvOusOcdcU

{
  "text": "This is great work. I am very glad. Everything is high quality.",
  "taskId": 1,
  "rating": 3,
  "customerId": "f4a981e3-73d0-41e9-8949-8f81dde8c16c",
  "contractorId": "88a30345-f1c6-4ba8-8e82-1bbb3444917e"
}



### Получение списка комментариев для определенного задания
GET http://localhost:3004/tasks/1/comments?page=1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmNGE5ODFlMy03M2QwLTQxZTktODk0OS04ZjgxZGRlOGMxNmMiLCJlbWFpbCI6ImpvaG4zQGRvZS5jb20iLCJyb2xlSWQiOjEsImxhc3RuYW1lIjoiRG9lIiwiZmlyc3RuYW1lIjoiSm9obiIsImlhdCI6MTcwNjgxOTkzMiwiZXhwIjoxNzA2ODIwMjMyfQ.pH0p_efnbYasVxLTiU4hqWNJqjJ8n2SfdfT0oiHzLOg



### Удаление всех комментариев задания
DELETE http://localhost:3004/tasks/1/comments HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmNGE5ODFlMy03M2QwLTQxZTktODk0OS04ZjgxZGRlOGMxNmMiLCJlbWFpbCI6ImpvaG4zQGRvZS5jb20iLCJyb2xlSWQiOjEsImxhc3RuYW1lIjoiRG9lIiwiZmlyc3RuYW1lIjoiSm9obiIsImlhdCI6MTcwNjgxOTkzMiwiZXhwIjoxNzA2ODIwMjMyfQ.pH0p_efnbYasVxLTiU4hqWNJqjJ8n2SfdfT0oiHzLOg



### Создание нового комментария
POST http://localhost:3004/tasks/comments HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmNGE5ODFlMy03M2QwLTQxZTktODk0OS04ZjgxZGRlOGMxNmMiLCJlbWFpbCI6ImpvaG4zQGRvZS5jb20iLCJyb2xlSWQiOjEsImxhc3RuYW1lIjoiRG9lIiwiZmlyc3RuYW1lIjoiSm9obiIsImlhdCI6MTcwNjgyMDk4OSwiZXhwIjoxNzA2ODIxMjg5fQ.nnKSg7tiD0bk0_O2EbyjgIxA2My4Z1APo1XolUjK6L8

{
  "text": "Some comment text",
  "taskId": 1
}



### Удаление комментария
DELETE http://localhost:3004/tasks/comments/14 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4OGEzMDM0NS1mMWM2LTRiYTgtOGU4Mi0xYmJiMzQ0NDkxN2UiLCJlbWFpbCI6ImpvaG40QGRvZS5jb20iLCJyb2xlSWQiOjIsImxhc3RuYW1lIjoiUnVzc2VsIiwiZmlyc3RuYW1lIjoiSmFjayIsImlhdCI6MTcwNjgyMTA5NywiZXhwIjoxNzA2ODIxMzk3fQ.gEVnBfi_N7q2igQosLdusPlvZ4i6Gu0Vij6oeIYA0Cg
