### Получение детальной информации о пользователе
GET http://localhost:3000/api/v1/users/4b43c48a-55da-431a-af9d-f23b0843a4f6 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0YjQzYzQ4YS01NWRhLTQzMWEtYWY5ZC1mMjNiMDg0M2E0ZjYiLCJlbWFpbCI6ImpvaG4xQGRvZS5jb20iLCJyb2xlSWQiOjEsImxhc3RuYW1lIjoiRG9lIiwiZmlyc3RuYW1lIjoiSm9obiIsImlhdCI6MTcwNjMxMjQ1MiwiZXhwIjoxNzA2MzEyNzUyfQ.GrVBF8FXKNuZLLwRZKzLe8E1HxWitBpa6VP-N2QL_xw



### Изменение информации профиля
PATCH  http://localhost:3000/api/v1/users/262666df-cff6-46d8-814a-51da7e00cbf4/profile HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyNjI2NjZkZi1jZmY2LTQ2ZDgtODE0YS01MWRhN2UwMGNiZjQiLCJlbWFpbCI6ImpvaG44MkBkb2UuY29tIiwicm9sZUlkIjoyLCJsYXN0bmFtZSI6IkRvZSIsImZpcnN0bmFtZSI6IkpvaG4iLCJpYXQiOjE3MDYwMzMwODAsImV4cCI6MTcwNjAzMzM4MH0.GxkV4-fZCfeKpEkP3d65sUiHDagBa7QOykvsRuvUYTo

{
  "firstname": "Jack",
  "lastname": "Russel",
  "info": "Some text",
  "specializations": ["t1"]
}
