### Получение списка статусов заданий
GET http://localhost:3004/references/statuses HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjMWIxOTk1MS01MDllLTRlMWMtOTc2ZC1iMDdhNmI1Y2E5OWMiLCJlbWFpbCI6ImpvaG44MUBkb2UuY29tIiwicm9sZUlkIjoxLCJsYXN0bmFtZSI6IkRvZSIsImZpcnN0bmFtZSI6IkpvaG4iLCJpYXQiOjE3MDU3NDY2MjEsImV4cCI6MTcwNTc0NjkyMX0.Cu-Ad3Y9OtrtlYL8-ayy_0F4YFknOB2Xy5ikjATkATo


### Получение детальной информации о статусе
GET http://localhost:3004/references/statuses/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjMWIxOTk1MS01MDllLTRlMWMtOTc2ZC1iMDdhNmI1Y2E5OWMiLCJlbWFpbCI6ImpvaG44MUBkb2UuY29tIiwicm9sZUlkIjoxLCJsYXN0bmFtZSI6IkRvZSIsImZpcnN0bmFtZSI6IkpvaG4iLCJpYXQiOjE3MDU3NDY2MjEsImV4cCI6MTcwNTc0NjkyMX0.Cu-Ad3Y9OtrtlYL8-ayy_0F4YFknOB2Xy5ikjATkATo



### Получение списка городов
GET http://localhost:3004/references/cities HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjMWIxOTk1MS01MDllLTRlMWMtOTc2ZC1iMDdhNmI1Y2E5OWMiLCJlbWFpbCI6ImpvaG44MUBkb2UuY29tIiwicm9sZUlkIjoxLCJsYXN0bmFtZSI6IkRvZSIsImZpcnN0bmFtZSI6IkpvaG4iLCJpYXQiOjE3MDU3NDYyODksImV4cCI6MTcwNTc0NjU4OX0.4F_BxZ4jS2sQSQaPgKSciOL2wlSbtwlRFNAgux7PG28



### Получение детальной информации о городе
GET http://localhost:3004/references/cities/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjMWIxOTk1MS01MDllLTRlMWMtOTc2ZC1iMDdhNmI1Y2E5OWMiLCJlbWFpbCI6ImpvaG44MUBkb2UuY29tIiwicm9sZUlkIjoxLCJsYXN0bmFtZSI6IkRvZSIsImZpcnN0bmFtZSI6IkpvaG4iLCJpYXQiOjE3MDU3NDYyODksImV4cCI6MTcwNTc0NjU4OX0.4F_BxZ4jS2sQSQaPgKSciOL2wlSbtwlRFNAgux7PG28



### Получение списка ролей
GET  http://localhost:3004/references/roles HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyOWJlMmJhZS00ZGQ3LTRiZjQtOTQ3ZC04NzJlZDUwZTZiMDYiLCJlbWFpbCI6ImpvaG44NEBkb2UuY29tIiwicm9sZUlkIjoyLCJsYXN0bmFtZSI6IkRvZSIsImZpcnN0bmFtZSI6IkpvaG4iLCJpYXQiOjE3MDU3MDEwOTQsImV4cCI6MTcwNTcwMTM5NH0.64ylgldywEcO4Vq2GELifjpByaDh3pqjb7uTNAlBxYE



### Получение детальной информации о роли
GET http://localhost:3004/references/roles/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyOWJlMmJhZS00ZGQ3LTRiZjQtOTQ3ZC04NzJlZDUwZTZiMDYiLCJlbWFpbCI6ImpvaG44NEBkb2UuY29tIiwicm9sZUlkIjoyLCJsYXN0bmFtZSI6IkRvZSIsImZpcnN0bmFtZSI6IkpvaG4iLCJpYXQiOjE3MDU3MDEwOTQsImV4cCI6MTcwNTcwMTM5NH0.64ylgldywEcO4Vq2GELifjpByaDh3pqjb7uTNAlBxYE
