services:
  taskforce.user.postgres:
    env_file:
      - env/.dev.env

  taskforce.user.pgadmin:
    container_name: taskforce.user.pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_CONFIG_SESSION_COOKIE_NAME: '"taskforce_user_cookie"'
    env_file:
      - env/.dev.env
    ports:
      - '8083:80'
    volumes:
      - user-pgadmin:/var/lib/pgadmin
    networks:
      - taskforce-user
    restart: unless-stopped

volumes:
  user-pgadmin:
