### Создание нового комментария
POST  http://localhost:3002/api/v1/comments HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjMWIxOTk1MS01MDllLTRlMWMtOTc2ZC1iMDdhNmI1Y2E5OWMiLCJlbWFpbCI6ImpvaG44MUBkb2UuY29tIiwicm9sZUlkIjoxLCJsYXN0bmFtZSI6IlJ1c3NlbCIsImZpcnN0bmFtZSI6IkphY2siLCJpYXQiOjE3MDYxNDM2MjQsImV4cCI6MTcwNjE0MzkyNH0.0jBiDTJ4v9cSB_N3W1RRegV6wQxpJ81BKXjOYl5G6OU

{
  "text": "Some comment text",
  "taskId": 1
}



### Удаление комментария
DELETE  http://localhost:3002/api/v1/comments/26 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjMWIxOTk1MS01MDllLTRlMWMtOTc2ZC1iMDdhNmI1Y2E5OWMiLCJlbWFpbCI6ImpvaG44MUBkb2UuY29tIiwicm9sZUlkIjoxLCJsYXN0bmFtZSI6IlJ1c3NlbCIsImZpcnN0bmFtZSI6IkphY2siLCJpYXQiOjE3MDYxMDk5MzcsImV4cCI6MTcwNjExMDIzN30.UJDyIOG6HHAA2GpX2hEi8jazDpTjN9x8dSx2myUr5QI
