### Создание нового комментария
POST  http://localhost:3002/api/v1/comments HTTP/1.1
Content-Type: application/json

{
  "text": "Some comment text",
  "taskId": 1
}



### Удаление комментария
DELETE  http://localhost:3002/api/v1/comments/13 HTTP/1.1
Content-Type: application/json



### Получение списка комментариев для определенного задания
GET  http://localhost:3002/api/v1/tasks/1/comments HTTP/1.1
Content-Type: application/json



### Удаление всех комментариев задания
DELETE  http://localhost:3002/api/v1/tasks/1/comments HTTP/1.1
Content-Type: application/json
