### Создание нового задания
POST  http://localhost:3002/api/v1/tasks HTTP/1.1
Content-Type: application/json

{
  "title": "Task long long title",
  "description": "Objectively procrastinate dynamic imperatives without customer directed niches. Proactively productivate interdependent e-commerce and transparent methodologies.",
  "category": "мебель",
  "cityId": 1,
  "price": 1000,
  "tags": ["tt1"],
  "executionDate": "2024-01-05",
  "address": "Moscow, Presnenskaya embankment, 12, office No. 2"
}



### Получение списка заданий
GET  http://localhost:3002/api/v1/tasks?page=1&cityId=1&categoryId=1&tagId=5 HTTP/1.1
Content-Type: application/json



### Получение детальной информации о задаче
GET  http://localhost:3002/api/v1/tasks/1 HTTP/1.1
Content-Type: application/json



### Обновление данных по задаче
PATCH  http://localhost:3002/api/v1/tasks/1 HTTP/1.1
Content-Type: application/json

{
  "statusId": 2,
  "contractorId": "fbc55fd6-9ac2-4aad-8b79-5adfb2faed8d"
}



### Удаление существующей задачи
DELETE  http://localhost:3002/api/v1/tasks/1 HTTP/1.1
Content-Type: application/json



### Получение списка комментариев для определенного задания
GET  http://localhost:3002/api/v1/tasks/8/comments?page=1 HTTP/1.1
Content-Type: application/json



### Удаление всех комментариев задания
DELETE  http://localhost:3002/api/v1/tasks/1/comments HTTP/1.1
Content-Type: application/json
