### Создание нового задания
POST  http://localhost:3002/api/v1/tasks HTTP/1.1
Content-Type: application/json

{
  "title": "Task title",
  "description": "Task's extended description",
  "category": "engineering",
  "city": "Moscow",
  "price": "1000",
  "executionDate": "2023-23-04T08:55:00.000Z",
  "address": "Moscow, Presnenskaya embankment, 12, office No. 2",
  "tags": ["engineering", "moscow"]
}



### Получение списка заданий
GET  http://localhost:3002/api/v1/tasks HTTP/1.1
Content-Type: application/json



### Получение детальной информации о задаче
GET  http://localhost:3002/api/v1/tasks/3154d38b-a3ae-440e-96db-8465d99411c3 HTTP/1.1
Content-Type: application/json



### Обновление данных по задаче
PATCH  http://localhost:3002/api/v1/tasks/3154d38b-a3ae-440e-96db-8465d99411c3 HTTP/1.1
Content-Type: application/json

{
  "status": "in-progress",
  "contractorId": "fbc55fd6-9ac2-4aad-8b79-5adfb2faed8d"
}



### Удаление существующей задачи
DELETE  http://localhost:3002/api/v1/tasks/3154d38b-a3ae-440e-96db-8465d99411c3 HTTP/1.1
Content-Type: application/json
