### Создание нового задания
POST  http://localhost:3002/api/v1/tasks HTTP/1.1
Content-Type: application/json

{
  "title": "Task title",
  "description": "Task's extended description",
  "categoryId": 1,
  "cityId": 1,
  "statusId": 1,
  "price": 1000,
  "executionDate": "2023-12-25T00:00:00.000Z",
  "address": "Moscow, Presnenskaya embankment, 12, office No. 2"
}



### Получение списка заданий
GET  http://localhost:3002/api/v1/tasks HTTP/1.1
Content-Type: application/json



### Получение детальной информации о задаче
GET  http://localhost:3002/api/v1/tasks/1 HTTP/1.1
Content-Type: application/json



### Обновление данных по задаче
PATCH  http://localhost:3002/api/v1/tasks/1 HTTP/1.1
Content-Type: application/json

{
  "statusId": 2,
  "contractorId": "fbc55fd6-9ac2-4aad-8b79-5adfb2faed8d"
}



### Удаление существующей задачи
DELETE  http://localhost:3002/api/v1/tasks/1 HTTP/1.1
Content-Type: application/json
