services:
  taskforce.notify.rabbitmq:
    env_file:
      - env/.dev.env

  taskforce.notify.mongo:
    env_file:
      - env/.dev.env

  taskforce.notify.mongo.ui:
    container_name: taskforce.notify.mongo.ui
    image: mongo-express
    ports:
      - '8084:8081'
    env_file:
      - env/.dev.env
    depends_on:
      - taskforce.notify.mongo
    restart: always
