services:
  taskforce.image.mongo:
    env_file:
      - env/.dev.env

  taskforce.image.mongo.ui:
    container_name: taskforce.image.mongo.ui
    image: mongo-express
    ports:
      - '8081:8081'
    env_file:
      - env/.dev.env
    depends_on:
      - taskforce.image.mongo
    restart: always

