version: '3.5'
services:
  taskforce.task.postgres:
    container_name: taskforce.task.postgres
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    volumes:
      - taskforce-task:/var/lib/postgresql/data
    networks:
      - taskforce-task
    restart: unless-stopped

networks:
  taskforce-task:
    driver: bridge

volumes:
  taskforce-task:
