services:
  taskforce.task.postgres:
    env_file:
      - env/.dev.env

  taskforce.task.pgadmin:
    container_name: taskforce.task.pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_CONFIG_SESSION_COOKIE_NAME: '"taskforce_task_cookie"'
    env_file:
      - env/.dev.env
    ports:
      - '8082:80'
    volumes:
      - task-pgadmin:/var/lib/pgadmin
    networks:
      - taskforce-task
    restart: unless-stopped

volumes:
  task-pgadmin:
