### Регистрация нового пользователя
POST http://localhost:3000/api/v1/auth/register HTTP/1.1
Content-Type: application/json

{
  "firstname": "John",
  "lastname": "Doe",
  "email": "john9@doe.com",
  "cityId": 2,
  "roleId": 1,
  "password": "123456",
  "birthDate": "2004-12-29"
}



### Логин пользователя в систему
POST http://localhost:3000/api/v1/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "john9@doe.com",
  "password": "123456"
}



### Изменение пользовательского пароля
PATCH  http://localhost:3000/api/v1/auth/password/963d1b4e-2979-403e-a107-4bb40f7d1cb3 HTTP/1.1
Content-Type: application/json

{
  "oldPassword": "123456",
  "newPassword": "567890"
}



### Выход из авторизованной зоны
POST  http://localhost:3000/api/v1/auth/logout HTTP/1.1
Content-Type: application/json



### Обновление токенов
POST  http://localhost:3000/api/v1/auth/tokens HTTP/1.1
Content-Type: application/json

{
  "refreshToken": "123fsd4fk4jf43sd4kr43kd4ff4ds"
}
