### Регистрация нового пользователя
POST http://localhost:3000/api/v1/auth/register HTTP/1.1
Content-Type: application/json

{
  "firstname": "John",
  "lastname": "Doe",
  "email": "john11@doe.com",
  "cityId": 2,
  "roleId": 1,
  "password": "123456",
  "birthDate": "2004-12-29"
}



### Логин пользователя в систему
POST http://localhost:3000/api/v1/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "john2@doe.com",
  "password": "123456"
}



### Изменение пользовательского пароля
PATCH  http://localhost:3000/api/v1/auth/password/2a51e38a-2614-4907-ae7a-c706c00b919b HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyYTUxZTM4YS0yNjE0LTQ5MDctYWU3YS1jNzA2YzAwYjkxOWIiLCJlbWFpbCI6ImpvaG45NTg1NEBkb2UuY29tIiwicm9sZUlkIjoxLCJsYXN0bmFtZSI6IkRvZSIsImZpcnN0bmFtZSI6IkpvaG4iLCJpYXQiOjE3MDUwNDkwMTcsImV4cCI6MTcwNTA0OTMxN30.pk80-RK_mKG18TuJHan4WP2krTk2pGIEnX0zTt70sWE

{
  "oldPassword": "123456",
  "newPassword": "567890"
}



### Получение информации о пользователе из заголовка Authorization
POST  http://localhost:3000/api/v1/auth/check HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjNWU0NDEzNy1mYzA2LTQ4NTItYTcwMi1hZWRmZGRmZTE4YzIiLCJlbWFpbCI6ImpvaG4zM0Bkb2UuY29tIiwicm9sZUlkIjoyLCJsYXN0bmFtZSI6IkRvZSIsImZpcnN0bmFtZSI6IkpvaG4iLCJpYXQiOjE3MDU1MTIwOTEsImV4cCI6MTcwNTUxMjM5MX0.tn6zqTbk2Mdvvmu97hrrQo0SEU_1t3Q_anPMREfEzSw



